[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[environments.production.domains]
# カスタムドメイン設定
domains = ["dive-buddys.com", "www.dive-buddys.com"]

[environments.production.services.web]
# HTTPSリダイレクト強制
httpsOnly = true
# HSTS設定
headers = { "Strict-Transport-Security" = "max-age=31536000; includeSubDomains" }