# ELK Stack - Elasticsearch, Logstash, Kibana
# 完全無料構成でのログ監視システム

version: '3.8'

services:
  # Elasticsearch - ログデータの保存・検索
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: jiji-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config:/usr/share/elasticsearch/config
    networks:
      - elk-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Logstash - ログデータの処理・変換
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: jiji-logstash
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ../logs:/usr/share/logstash/logs:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    networks:
      - elk-network
    depends_on:
      - elasticsearch
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Kibana - ログデータの可視化・分析
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: jiji-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    networks:
      - elk-network
    depends_on:
      - elasticsearch
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Filebeat - ログファイルの監視・転送
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: jiji-filebeat
    user: root
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../logs:/usr/share/filebeat/logs:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - elk-network
    depends_on:
      - elasticsearch
      - logstash
    restart: unless-stopped
    command: filebeat -e -strict.perms=false

  # Metricbeat - システムメトリクスの監視
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.11.0
    container_name: jiji-metricbeat
    user: root
    volumes:
      - ./metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - elk-network
    depends_on:
      - elasticsearch
    restart: unless-stopped
    command: metricbeat -e -strict.perms=false

networks:
  elk-network:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local