# Jijiダイビングボット アラートルール
groups:
  - name: jiji-system-alerts
    rules:
      # システムリソース監視
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: system
        annotations:
          summary: "CPU使用率が高い状態が続いています"
          description: "{{ $labels.instance }} のCPU使用率が {{ $value }}% を超えています"
          
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: system
        annotations:
          summary: "メモリ使用率が高い状態が続いています"
          description: "{{ $labels.instance }} のメモリ使用率が {{ $value }}% を超えています"
          
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"}) * 100 < 10
        for: 5m
        labels:
          severity: critical
          service: jiji-diving-bot
          category: system
        annotations:
          summary: "ディスク容量が不足しています"
          description: "{{ $labels.instance }} の {{ $labels.mountpoint }} の空き容量が {{ $value }}% を下回りました"

  - name: jiji-application-alerts
    rules:
      # アプリケーション監視
      - alert: ApplicationDown
        expr: up{job="jiji-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: jiji-diving-bot
          category: application
        annotations:
          summary: "Jijiアプリケーションが停止しています"
          description: "{{ $labels.instance }} でアプリケーションが1分間停止しています"
          
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 3m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: performance
        annotations:
          summary: "レスポンス時間が遅い状態が続いています"
          description: "95パーセンタイルのレスポンス時間が {{ $value }}秒 を超えています"
          
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 3m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: application
        annotations:
          summary: "エラー率が高い状態が続いています"
          description: "5xxエラーの発生率が {{ $value }}% を超えています"
          
      - alert: HighRequestRate
        expr: rate(http_requests_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: traffic
        annotations:
          summary: "リクエスト数が急増しています"
          description: "1秒あたりのリクエスト数が {{ $value }} を超えています"

  - name: jiji-security-alerts
    rules:
      # セキュリティ監視
      - alert: RateLimitExceeded
        expr: increase(rate_limit_exceeded_total[5m]) > 10
        for: 1m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: security
        annotations:
          summary: "レート制限が頻繁に発生しています"
          description: "過去5分間で {{ $value }} 回のレート制限が発生しました"
          
      - alert: SuspiciousActivity
        expr: increase(security_events_total{type="suspicious"}[5m]) > 5
        for: 1m
        labels:
          severity: critical
          service: jiji-diving-bot
          category: security
        annotations:
          summary: "疑わしい活動が検出されました"
          description: "過去5分間で {{ $value }} 回の疑わしい活動が検出されました"
          
      - alert: AuthenticationFailures
        expr: increase(auth_failures_total[5m]) > 20
        for: 2m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: security
        annotations:
          summary: "認証失敗が頻発しています"
          description: "過去5分間で {{ $value }} 回の認証失敗が発生しました"

  - name: jiji-database-alerts
    rules:
      # データベース監視
      - alert: DatabaseConnectionsHigh
        expr: pg_stat_activity_count > 80
        for: 2m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: database
        annotations:
          summary: "データベース接続数が多い状態です"
          description: "データベース接続数が {{ $value }} を超えています"
          
      - alert: SlowQueries
        expr: pg_stat_activity_max_tx_duration > 30
        for: 1m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: database
        annotations:
          summary: "遅いクエリが実行されています"
          description: "30秒以上実行されているクエリがあります"

  - name: jiji-external-alerts
    rules:
      # 外部サービス監視
      - alert: ExternalServiceDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
          service: jiji-diving-bot
          category: external
        annotations:
          summary: "外部サービスが利用できません"
          description: "{{ $labels.instance }} が1分間応答していません"
          
      - alert: SSLCertificateExpiry
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1m
        labels:
          severity: warning
          service: jiji-diving-bot
          category: ssl
        annotations:
          summary: "SSL証明書の有効期限が近づいています"
          description: "{{ $labels.instance }} のSSL証明書が7日以内に期限切れになります"