# Prometheus設定 - Jijiダイビングボット監視
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'jiji-diving-bot'
    environment: 'production'

# アラートルール設定
rule_files:
  - "rules/*.yml"

# アラート送信設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# メトリクス収集設定
scrape_configs:
  # Prometheusサーバー自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    
  # Node Exporter - システムメトリクス
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    
  # cAdvisor - コンテナメトリクス
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    
  # Jijiアプリケーション - カスタムメトリクス
  - job_name: 'jiji-app'
    static_configs:
      - targets: ['host.docker.internal:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    
  # Blackbox Exporter - 外形監視
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://jiji-diving-bot.railway.app/health
        - https://jiji-diving-bot.railway.app/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
        
  # SSL証明書監視
  - job_name: 'ssl-check'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://jiji-diving-bot.railway.app
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
        
  # データベース監視（Supabase）
  - job_name: 'database'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    
  # Redis監視
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s